### ISSUE TITLE
Link  Broken

### ISSUE THREAD

**Issue by rbgodwin** [AMWA-TV/nmos-sink-metadata-processing#107]
On the rendered page:

https://specs.amwa.tv/is-11/branches/v1.0-dev/docs/Overview.html#introduction

The link to Resource Core JSON Schema is broken

Steps to reproduce.
1) Open page https://specs.amwa.tv/is-11/branches/v1.0-dev/docs/Overview.html#introduction
2) Click on Link for Resource Core JSON Schema

Expected behavior 
Link opens

Observed Behavior
Link does not open

Extra Hints:

 Works ok on the actual repo.
 Looks like a double use of with-refs.
  Link broken link is: https://specs.amwa.tv/is-04/releases/v1.3.2/APIs/schemas**/with-refs/with-refs/**resource_core.html

**Comment by garethsb** [comment]
Sorry, yes, already tracked here - https://github.com/AMWA-TV/is-11/pull/106#issuecomment-1242636229
