### ISSUE TITLE
Constraint Set metadata are not Parameter Constraints

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-sink-metadata-processing#121]
https://github.com/AMWA-TV/is-11/blob/83169a2dd2d11c9d804072945da0dd5dad991b39/docs/Behaviour%20-%20Server%20Side.md?plain=1#L14-L17

According to BCP-004-01, "the `<category>` name `meta` is reserved for metadata related to Constraint Sets. These attributes are not constraints themselves."

Could we specify that all Senders have to support these `meta` attributes, and that they won't be listed in _/supported_ endpoint? (They can just choose to ignore `meta:label` and `meta:preference` if they want to I think, so it's only `meta:enabled` that they pro-actively have to support?)

We'd omit the `meta` from here too:

https://github.com/AMWA-TV/is-11/blob/83169a2dd2d11c9d804072945da0dd5dad991b39/APIs/schemas/constraints_supported.json#L8-L17

And change this pattern to `"^urn:x-nmos:cap:(?!meta:)"`:

https://github.com/AMWA-TV/is-11/blob/83169a2dd2d11c9d804072945da0dd5dad991b39/APIs/schemas/constraints_supported.json#L31

**Comment by alabou** [comment]
I think we can fix the normative language to indicate that meta are required but that they are not parameter constraints ... but I would still list them in /supported such that is is clear that those are supported and if new meta are added implementation will opt-in by listing them.

My vote is to fix the normative language only.

**Comment by alabou** [comment]
What about this?

"A Sender MUST present the list of supported parameter constraints and metadatas in `/supported` endpoint. This list MUST include at least the parameter constraints and metadatas from the following list which are applicable to the format of the Flow associated with this Sender: "

**Comment by garethsb** [comment]
I think we all agree that all implementations MUST support the current `metadata`?

I can see your rationale for including the Constraint Set Metadata in the _/supported_ endpoint even so, as it gives us some flexibility if BCP-004-01 v1.1 comes along and introduces more.

Since constraint set metadata is not related to format, I just tweak your proposed wording slightly:

"A Sender MUST present the list of supported constraint set metadata and parameter constraints in the _/supported_ endpoint. This list MUST include the three constraint set metadata and at least those parameter constraints from the following list which are applicable to the format of the Flow associated with this Sender:"

**Comment by alabou** [comment]
You sentence seems to implies a pre-defined set of metadata ... I would follow the same pattern as for the parameter constraints ... "at least those ... from the following list"

"A Sender MUST present the list of supported constraint set metadata and parameter constraints in the /supported endpoint. This list MUST include at least those constraint set metadata from the following list and at least those parameter constraints from the following list which are applicable to the format of the Flow associated with this Sender:"
