### ISSUE TITLE
Should we make IS-11 schemas self contained?

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-sink-metadata-processing#125]
https://github.com/AMWA-TV/is-11/blob/ff335ee226b8190ae5d79b4d81936e338ec2f95e/APIs/schemas/constraints_active.json#L13

https://github.com/AMWA-TV/is-11/blob/ff335ee226b8190ae5d79b4d81936e338ec2f95e/APIs/schemas/input.json#L7

https://github.com/AMWA-TV/is-11/blob/ff335ee226b8190ae5d79b4d81936e338ec2f95e/APIs/schemas/output.json#L7

**Comment by garethsb** [comment]
Also a different reference to the same logical thing...

https://github.com/AMWA-TV/is-11/blob/33b981ef9d4f8903df3004f8a813ac64a02038c4/APIs/schemas/empty_constraints_active.json#L12

**Comment by garethsb** [comment]
Discussed in ARG call today - we probably want a version of IS-11 to use a specific version of these schemas (i.e. not `v1.0.x` branch!). Using external `http` references probably also breaks air-gapped test tool? So probably better to copy necessary schemas into IS-11.

**Comment by alabou** [comment]
For resource core, because Input and Output are not in the registry we can have an IS-11 flavor of a resource core ... But for capabilities and constraint sets we cannot ... IS-11 and other NMOS API must be using the same definition of a constraint set. It makes no sense to allow using something which is not 100% compatible so in this case I don't think that having copies is the right way to go. There is still the issue at getting a consistent IS-11 and there is a dependency on the BCP-004-01 version being used.

**Comment by peterbrightwell** [comment]
Architecture Review Group review: place on backlog

**Comment by garethsb** [comment]
Cf. also https://github.com/AMWA-TV/is-07/issues/26

**Comment by N-Nagorny** [comment]
Ways of tackling this issue from the call:
1. Direct `$ref`s to specs.amwa.tv.
:heavy_plus_sign: `$ref`s are GitHub agnostic
:heavy_plus_sign: `$ref`s point to a specific tag of a dependency
:heavy_plus_sign: Changing tag of a dependency as part of a spec update is easily traceable
:heavy_plus_sign: No duplication
:heavy_minus_sign: Air-gapped tools should care about `$ref`s
2. Copy necessary schemas from a dependency to `APIs/schemas`, add `README.md` to `APIs/schemas` and add normative language.
:heavy_plus_sign: Air-gapped tools should not care about `$ref`s
:heavy_plus_sign: Changing tag of a dependency as part of a spec update is traceable via `README.md`
:heavy_minus_sign: Duplication
:heavy_minus_sign: May be hard to distinct copied schemas from original ones
3. Copy necessary schemas from a dependency to `APIs/schemas`, add a dependency identifying prefix to their names, add `README.md` to `APIs/schemas` and add normative language.
:heavy_plus_sign: Air-gapped tools should not care about `$ref`s
:heavy_plus_sign: Changing tag of a dependency as part of a spec update is traceable via `README.md`
:heavy_plus_sign: Easy to distinct copied schemas from original ones
:heavy_minus_sign: Duplication
:heavy_minus_sign: Need to rename schemas from a dependency and change existing local `$ref`s
4. git submodule for a dependency
:heavy_minus_sign: Air-gapped tools should care about `$ref`s
:heavy_plus_sign: It's a 'standard' way of air-gapping preparations
:heavy_plus_sign: Changing tag of a dependency as part of a spec update is traceable (as commit ID change)
:heavy_plus_sign: No duplication
:heavy_minus_sign: May affect existing tooling
:heavy_minus_sign: Users are supposed to do extra actions after cloning the repo
5. Copy necessary schemas to `APIs/schemas/{dependency_name}/{dependency_tag}`
:heavy_plus_sign: Air-gapped tools should not care about `$ref`s
:heavy_plus_sign: Changing tag of a dependency as part of a spec update is traceable
:heavy_minus_sign: Duplication
:heavy_minus_sign: Not all JSON Schema resolvers work with deep directory trees

**Comment by garethsb** [comment]
> For resource core, because Input and Output are not in the registry we can have an IS-11 flavor of a resource core ... 

Agreed, we have the same _resource_core.json_ not because IS-11 "must" use the same schema as IS-04, but because we want IS-11 resources to be in the spirit of IS-04 ones. In the same way as we want the same _error.json_ schema to provide familiarity, a family resemblance, for implementers.

> But for capabilities and constraint sets we cannot ... IS-11 and other NMOS API must be using the same definition of a constraint set. 

I look at this a slightly different way. IS-11 v1.0 needs to express active constraints. It chooses to do so in the same way as BCP-004-01 v1.0.

If there were in the future a BCP-004-01 v1.1 or an IS-11 v1.1, then a controller would need to know (a) the version of both specs being used by each Sender and Receiver, and (b) how to convert between the different expressions (maybe it won't be possible, maybe it will require a complicated filtering/conversion, or maybe they will be sufficiently inter-version compatible that the controller need do nothing since the API implementations will ignore anything new...).

What does that mean at **this** point in time?

* We should be clear how an IS-11 API implementation handles a JSON request that is not valid per the schema
  * I think we've already done that
* We should be clear how an IS-11 API implementation handles a JSON request that is valid but has new attributes
  * E.g. ignores them (I think this is assumed at least)
* We should be clear how an IS-11 API implementation handles a JSON request that has unrecognized values (constraint names or values)
  * I think we've done that too?
* We should provide guidance to the future authors of spec revisions as to what freedom they have when extending either BCP-004-01 or IS-11
  * I think we have unwritten AMWA leadership and community opinion on this to maintain backward compatibility _so long as it doesn't hold back our agile approach_. I don't think we ought to paralyze our current work to come up with definitive all-encompassing rules on what this means, but maybe some written bullet points would be beneficial!

With this view, my opinion is that the _expression_ of constraints is the same as BCP-004-01 v1.0 is a "very happy coincidence", but this fact needn't be "explicitly encoded" into the rendered spec or even its repo via out-of-tree references whether via `$ref` or git submodules. I think specification text is sufficient if having copies of the schema files simplifies API implementations and AMWA test suite and documentation tooling at this time.

**Comment by garethsb** [comment]
Discussed in ARG. Agree copies are uncomfortable, but since the intent is not to allow a Stream Compatibility API v1.0 to "host" BCP-004-01 future v1.1, v1.2 constraint_sets, the schema copies are the least worst option for now. ARG will monitor as new spec versions and any other similar "mix-in" schemas are being created.
