### ISSUE TITLE
Modifiying Base EDID on its way to become Effective EDID

### ISSUE THREAD

**Issue by N-Nagorny** [AMWA-TV/nmos-sink-metadata-processing#132]
> Effective EDID is such combination of Base EDID and Active Constraints of all Senders associated with this Input that the baseband signal from the Input can be transmitted by the Senders without breaking Active Constraints.
>
> If Base EDID is not set, Effective EDID is built on the basis of a default Base EDID defined for the Input by the manufacturer.

Although these paragraphs say that Effective EDID is Base EDID (or vendor's EDID) modified by Active Constraints, there is a nuance here. If Base EDID is not set by a user, the vendor's EDID, that is used instead, stores information about capabilities of the Input. When Base EDID is set, these capabilities are lost. Sometimes, we want to lose them and set exactly what the user wants. In this case there is a risk that a source will start giving unsupported signal, so we may want to modify Base EDID to fix that. We might solve it via PUTting Active Constraints, but we don't know how to build them because the capabilities of the Input are lost. In this case, it may be beneficial to let Input itself modify Base EDID based on its capabilities before applying Active Constraints to Base EDID.

For me, it looks like a flag for PUT `/edid/base` operation that specifies whether an Input is allowed to modify Base EDID if Active Constraints are not set. Its implementation may consist of two parts:
1. An Input's property like `base_edid_support` (`base_edid_alterable`?) showing whether this Input supports such a flag.
2. A flag itself implemented as an additional request header or as a `multipart/form-data`'s property or a property of another resource like `/inputs/{inputId}/properties`.

**Comment by alabou** [comment]
There is no need to change the actual behavior and specification of IS-11. If a Controller wants its Base EDID to be altered by the capabilities of the Input it can simply PUT active constraints that are not constraining the Sender at all. This will allow the device to derive the Effective EDID from the capabilities of the Input and the BASE EDID . Simple constraints like "urn:x-nmos:cap:format:frame_width":{}, "urn:x-nmos:cap:format:frame_height":{} would work as it indicate that the Controller don't care about the Flow attributes and that it only wants the device to use Base EDID and internal device capabilities to produce an Effective EDID for the Input.

**Comment by N-Nagorny** [comment]
An idea from the call: add optional query parameter to the PUT `/edid/base` for the mentioned behavior.
