### ISSUE TITLE
Should /sinks have similar subroutes to /senders and /receivers?

### ISSUE THREAD

**Issue by N-Nagorny** [AMWA-TV/nmos-sink-metadata-processing#17]
`/senders/`/ `/receivers/` + `resource ID` return a subroute. `/sinks/` + `Sink ID` returns a Sink JSON, hiding `/edid` subroute. Should we remake this in the consistent way?

**Comment by N-Nagorny** [comment]
@cristian-recoseanu proposed the following option:
```
  /{sinkId}:
    get:
      responses:
        200:
          description: Returned when success.
          body:
            example: [ "self/", "edid/" ]
```

**Comment by N-Nagorny** [comment]
Another approach is adding a property similar to `manifest_href` to Sink. It solves the problem, seems consistent with IS-04, excludes any possibility of mislinking it with `self` in IS-04, adds a straightforward way to show it's `null` without an additional request and creates an opportunity to transfer responsibility of hosting EDIDs from Node itself to an underlying level if it already hosts EDIDs.

**Comment by cristian-recoseanu** [comment]
But transport files for RTP were originally found in the manifest_href in IS-04 and then moved to another API (IS-05). I don't believe the manifest href is a good pattern to follow but I might be wrong.

**Comment by prince-chrismc** [comment]
The `manifest_href` was a very complicated topic when we worked on IS-10 and BCP-003-2, https://specs.amwa.tv/bcp-003-02/releases/v1.0.0/docs/1.0._Authorization_Practice.html#node-manifest-href-authorization

I would prefer avoid that mechanic as well.

**Comment by N-Nagorny** [comment]
Another option is utilizing [HTTP Accept header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) for a single `sink/` endpoint. If the header is `application/json`, it returns Sink, otherwise it returns the binary EDID. But I don't lean to this much to keep place for Sinks without EDID.

**Comment by N-Nagorny** [comment]
@garethsb, could you take a look at this, please? It would be very helpful for us.

**Comment by garethsb** [comment]
Hi,

While using an `Accept` header seems initially attractive, I would vote against it because (a) I think it is much less 'discoverable' and (b) I suspect the JSON response and the EDID binary response do not contain quite the same information?

Regarding the idea of having the JSON response at `/sinks/{sinkId}` and the EDID response at `/sinks/{sinkId}/edid`, we have precedent for an endpoint under another one that doesn't have a 'child resources' response in IS-04 `/receivers/{receiverId}/target`, but since that's deprecated, it's not a great precedent, and I can't think of another one.

I'd go for the idea of having two 'side-by-side' endpoints; IS-08 uses `properties` (e.g. `/inputs/{inputId}/properties`) where you have suggested `self`, which I think would work well here.

**Comment by garethsb** [comment]
I agree with @cristian-recoseanu and @prince-chrismc regarding `manifest_href`, but there is another possibility which is to follow the model of IS-05 `/transportfile` which if I remember correctly SHOULD return the transport file directly, but MAY redirect with a `3xx` and `Location` to another URL. The same could be allowed for `/edid`?

By the way, my very limited understanding is that this API is meant to be generally useful for Sinks, so is `/edid` optional (i.e. allowed to return `404`)?

**Comment by N-Nagorny** [comment]
@garethsb, thank you for the help!

Right, the JSON response and the EDID binary response are not the same: EDID binary is taken 'as is' from underlying implementation when Sink is built from NMOS Resource and the most necessary fields parsed from EDID.

I think, redirection for `/edid` is a very good idea.

`/edid` is allowed to return `404` and I expect it will be the case for pure software implementations.

**Comment by prince-chrismc** [comment]
I like properties more then self 👍 

```raml
  /{sinkId}:
    get:
      responses:
        200:
          description: Returned when success.
          body:
            example: [ "properties/", "edid/" ]
```
