### ISSUE TITLE
Consistency and language issues

### ISSUE THREAD

**Issue by N-Nagorny** [AMWA-TV/nmos-sink-metadata-processing#18]
An issue for listing minor consistency problems.

The first one: `edid_timing.json` has `width` and `height` instead of `frame_width` and `frame_height`.

**Comment by prince-chrismc** [comment]
Closed by #16?

**Comment by N-Nagorny** [comment]
Unfortunately, no, but I created #21.

**Comment by N-Nagorny** [comment]
It's resolved in #21.
