### ISSUE TITLE
auto_sink-mp_10 fails due to schema violation

### ISSUE THREAD

**Issue by N-Nagorny** [AMWA-TV/nmos-sink-metadata-processing#23]
`auto_sink-mp_10` fails due to response schema violation. I need to figure out what's the reason.

**Comment by rbgodwin** [comment]
I captured a quick screenshot:
![image](https://user-images.githubusercontent.com/1545391/121674369-a374ca00-caba-11eb-8227-9c950a275087.png)

**Comment by N-Nagorny** [comment]
It's an issue in the Node implementation which is already fixed.

**Comment by prince-chrismc** [comment]
![image](https://user-images.githubusercontent.com/16867443/121693793-7367ff80-ca97-11eb-8f4c-cd4f417ec8e5.png)

For reference!
