### ISSUE TITLE
Making Media Profiles from Receiver Caps is not defined well

### ISSUE THREAD

**Issue by N-Nagorny** [AMWA-TV/nmos-sink-metadata-processing#27]
Receiver Caps is more flexible than Media Profiles, and when we prescribe making the second from the first, it raises question "If Receiver Caps don't constrain a parameter or do express a constraint with a range, should Controller create Media Profiles for all possible combinations of parameters matching the constraints?"

```
|                  Sender                   |                      |                Receiver                |
| HDMI Source <--> EDID <--> Media Profiles | <--> Controller <--> | Receiver Caps <--> EDID <--> HDMI Sink |
```

My proposal is to:
1. Expand IS-11 with a statement prescribing that Receivers listed in IS-11 MUST follow BCP-005-01.
2. Explicitly require `enum` usage for describing timings in BCP-005-01.
3. Add `required` fields to Media Profiles and state that absent fields mean any value of a parameter.

**Comment by prince-chrismc** [comment]
> 3\. Add `required` fields to Media Profiles and state that absent fields mean any value of a parameter.

These two clauses are in conflict. required fields can not be absent

**Comment by N-Nagorny** [comment]
I mean two subsets of properties: `required` and the rest. Any property of the latter may be absent and we can add language stating that the absence means any value admission.

**Comment by N-Nagorny** [comment]
Keep "frame_width", "frame_height", "grain_rate" for video and "media_type", "channel_count" for audio. Remove "media_type" for video at all.
