### ISSUE TITLE
Identifier Persistence for Sinks

### ISSUE THREAD

**Issue by prince-chrismc** [AMWA-TV/nmos-sink-metadata-processing#29]
As I recall this being something we mentioned in out calls but we currently have no documentation in our spec for if or when this should change.

- Can the GUID be persistent for the physical connection aka Sink and solely use the `version` (or the [capabilities version](https://specs.amwa.tv/bcp-004-01/releases/v1.0.0/docs/1.0._Receiver_Capabilities.html#capabilities-version)) change in the receiver core to signal a different physical device?
- Do we need to extent the [data model](https://specs.amwa.tv/is-04/releases/v1.3.1/docs/5.1._Data_Model_-_Identifier_Mapping.html#identifier-persistence--generation)? For when and when not to change the ID of a Sink

**Comment by cristian-recoseanu** [comment]
Does it follow the general NMOS ID guidelines or is that not sufficient? I agree we need to clarify when you should be using the same ID. In my head if it's the same monitor it should use the same sink ID.

**Comment by N-Nagorny** [comment]
All in favor that Sink ID should be changed only if physical monitor (or what plays its role) is changed.
