### ISSUE TITLE
Change name of display_type property to subsampling_modes?

### ISSUE THREAD

**Issue by cristian-recoseanu** [AMWA-TV/nmos-sink-metadata-processing#33]
https://github.com/AMWA-TV/nmos-sink-metadata-processing/blob/2df7505b0657cbd55b3981a5a838b237f058e206/APIs/schemas/edid.json#L43

The naming of this property isn't really consistent with its value type. It's an array so should we change its name to `subsampling modes`?

**Comment by prince-chrismc** [comment]
https://github.com/AMWA-TV/nmos-edid-to-receiver-caps-mapping/blob/v1.0-dev/docs/1.0.%20EDID%20to%20Receiver%20Caps%20mapping.md#color-subsampling

Maybe `color_sampling` to be consistent?

**Comment by N-Nagorny** [comment]
It's named `Supported Color Encoding Format/s` in the EDID spec, `Display type (digital)` in [Wikipedia](https://en.wikipedia.org/wiki/Extended_Display_Identification_Data#Structure,_version_1.4) and `Video Input Type` [here](https://www.extron.com/article/uedid).

With respect to Sink, I'd like to have names which are familiar to people working with EDID. `color_sampling` may confuse one even more.

**Comment by prince-chrismc** [comment]
#27 could resolve that. RX Caps mapping defines the connection to the EDID and within the NMOS we expose the "nmos terms" to be consistent against the other APIs

**Comment by cristian-recoseanu** [comment]
The thing I was trying to point out in the original comment was that in my mind a property which has an array as its value type should be called a term which is a plural.
