### ISSUE TITLE
Media profiles preference when connecting multiple receivers

### ISSUE THREAD

**Issue by cristian-recoseanu** [AMWA-TV/nmos-sink-metadata-processing#44]
What do we do when we get media profiles with different preferences from different receivers.
As we all know we have to generate common (intersection) media profiles from all the desired receivers but they may have different preferences.
Which one do we chose?
The one with the highest preference?

**Comment by prince-chrismc** [comment]
If they match (format) keep one/higher preference?

**Comment by cristian-recoseanu** [comment]
Yes the idea is what to do when generating the intersection and we have duplicate identical profiles but which might have different preferences.
> 
> 
> If they match (format) keep one/higher preference?

That's what our implementation does currently. But do we need to write this down in a document?

**Comment by N-Nagorny** [comment]
It's covered in https://github.com/AMWA-TV/is-11/pull/94.
