### ISSUE TITLE
Refreshing Media Profiles when number of connected receivers changes

### ISSUE THREAD

**Issue by cristian-recoseanu** [AMWA-TV/nmos-sink-metadata-processing#46]
I think we've discussed this but it probably needs written down.

If you have 3 receivers connected to an IS-11 sender and you disconnect one of them then the controller should re-PUT the media profiles because the intersection might be different and the sender might pick a different profile and create a new flow with better quality parameters.

On top of this we have the problem that this results in a new transport file for the sender.
So should the controller then "re-connect" all remaining receivers with the new transport file?
Whatever we decide it needs to be written down.

**Comment by cristian-recoseanu** [comment]
Furthermore I think this also applies to connecting a new receiver at a later point in time.
Should the controller re-connect all previous receivers with the new transport file?

**Comment by prince-chrismc** [comment]
Excellent topic... It depends on the User who may not want to interrupt the other two monitors. The same goes for adding one... does the user really want to if it does not meet the current media profile?

**Comment by cristian-recoseanu** [comment]
But the problem is you have no control over the sender. The sender will pick a new profile from the list and it will create a new flow and new transport file. The receivers might start receiving a different format stream from what the initial SDP file suggested...

**Comment by prince-chrismc** [comment]
My expectations as a Node...

1. media profiles is set
    a. negotiables with source
    b. update IS-04/SDP (min version max new flow)
    c. answer client
2. client gets SDP
3. client sets up IS-05 connection on Rx with SDP

...is that IS-11 will be configured before IS-05

I think we need a section like https://specs.amwa.tv/is-05/releases/v1.1.1/docs/1.0._Overview.html#api-interaction

**Comment by cristian-recoseanu** [comment]
That is a valid expectation. But IS-11 can be reconfigured after a receiver has already been connected which will change the SDP within an already common set of profiles. So the question still stands. Would the already connected receiver get confused when receiving something outside the original SDP?

**Comment by prince-chrismc** [comment]
> Would the already connected receiver get confused when receiving something outside the original SDP?

Yes. You'd want to break the connections, turn everything off, and then start over

**Comment by cristian-recoseanu** [comment]
> > Would the already connected receiver get confused when receiving something outside the original SDP?
> 
> Yes. You'd want to break the connections, turn everything off, and then start over

Wouldn't just applying the new SDP file and patching the receiver again fix the problem?

**Comment by prince-chrismc** [comment]
> Wouldn't just applying the new SDP file and patching the receiver again fix the problem?

Yes but then there's a risk the Receiver won't be happy...
if there's a resolution change it might not work, or if color change it wont work (during the time interval from `PUT /media-profiles` and `PATCH /stage` requests)

**Comment by N-Nagorny** [comment]
Reconnecting all the Receivers after Receiver set changes is a matter of policy of NMOS Controller. The spec now covers that NMOS Controller SHOULD PATCH /staged if Sender's transport file changed. https://github.com/AMWA-TV/is-11/blob/v1.0-dev/docs/Behaviour%20-%20Client%20Side.md#changes-which-do-not-break-active-constraints
