### ISSUE TITLE
Interlaced timing indication in /sinks/{sinkId}/properties

### ISSUE THREAD

**Issue by N-Nagorny** [AMWA-TV/nmos-sink-metadata-processing#56]
BCP-005-01 says
```
Each video timing SHOULD be present in the Receiver’s Capabilities as a Constraint Set with a non-empty

    urn:x-nmos:cap:format:frame_width
    urn:x-nmos:cap:format:frame_height
    urn:x-nmos:cap:format:grain_rate which MUST be the exact frame rate of the signal

The timing descriptors MAY include one or more of the following mappings:

    urn:x-nmos:cap:format:interlace_mode
    urn:x-nmos:cap:meta:preference
```

The first three properties are reflected in `edid_timing.json`. What do you think about adding an optional `interlace_mode` property?

BCP-005-01 does not dictate how to map an interlaced timing to video Flow `interlace_mode`. Does anybody know if it's appropriate to expose all three `interlaced_*` in this case?

**Comment by prince-chrismc** [comment]
I am in favor of adding it, it would be nice to match it to https://specs.amwa.tv/is-04/releases/v1.3.1/APIs/NodeAPI.html#flows__flowid__get

```
interlace_mode" : {
          "description" : "Interlaced video mode for frames in this Flow",
          "type" : "string",
          "default": "progressive",
          "enum" : [
            "progressive",
            "interlaced_tff",
            "interlaced_bff",
            "interlaced_psf"
          ]
```

**Comment by cristian-recoseanu** [comment]
Are we saying we are adding `interlaced_mode` to the video media profiles as optional and it will follow from the BCP-004-01 / Capabilities defined in the parameter register which actually will result in an enum with values taken from the flow interlace_mode?

From the parameter register capabilities:
Name: `urn:x-nmos:cap:format:interlace_mode`

```
    Description: Identifies the acceptable interlace mode of a video stream.
    Specification: per AMWA BCP-004-01
        Type: string (enumerated values as per AMWA IS-04)
        Target: (a) video Flow ‘interlace_mode’, (b) SDP attribute ‘a=fmtp:’ format-specific parameters ‘interlace’, ‘segmented’ and ‘top-field-first’
    Applicability: AMWA IS-04
```

**Comment by N-Nagorny** [comment]
`interlaced_mode` is already an optional property of video Media Profile. There is also `edid.json` on the Sink side which lists timings supported by the Sink. Each timing consists of frame size and rate and I propose to add optional `interlace_mode` to it.
