### ISSUE TITLE
Allow devices to respond with a `413 Payload Too Large` when receiving Media Profiles

### ISSUE THREAD

**Issue by prince-chrismc** [AMWA-TV/nmos-sink-metadata-processing#60]

**Comment by N-Nagorny** [comment]
If Controller gets 413 from IS-11, it should ask the user what to do as in the 500 case. The case of 413 is common for NMOS APIs. There are no reasons to add it to IS-11 without adding it to the other ISs. It would be good to raise it up in NMOS Architectural Review Group.

**Comment by garethsb** [comment]
Trying out tagging the @AMWA-TV/nmos-architecture-review group.
