### ISSUE TITLE
Adding additional Senders and Receivers

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-sink-metadata-processing#88]
I think this is probably out of scope for IS-11, and IS-11 configuration on its own is probably not enough, but has this group thought about an API mechanism to add and possibly remove Senders and Receivers?

(Current partial workaround for adding a new Sender could be to always have a "spare" unconfigured one which can then be configured using e.g. IS-11. Once it is configured a new "spare" would be created by the Node, up to whatever its limit is.)

**Comment by N-Nagorny** [comment]
This is a matter of Device configuration which is out of scope of IS-11. Closing it on the group call.
