### ISSUE TITLE
Media type only handles audio case

### ISSUE THREAD

**Issue by cristian-recoseanu** [AMWA-TV/nmos-sink-metadata-processing#9]
https://github.com/AMWA-TV/nmos-sink-metadata-processing/blob/28ceea56dbb72ed6d9b5943d4a5322864b4ca8ca/APIs/schemas/media_profile.json#L105

We need to revise the schema with regards to "media_type" as the current one only handles audio cases.

Here are some links from IS-04 schemas:
[flow_video_raw](https://specs.amwa.tv/is-04/branches/v1.1.x/APIs/schemas/with-refs/flow_video_raw.html)
[flow_video_coded](https://specs.amwa.tv/is-04/branches/v1.1.x/APIs/schemas/with-refs/flow_video_coded.html)
[flow_sdianc_data](https://specs.amwa.tv/is-04/branches/v1.1.x/APIs/schemas/with-refs/flow_sdianc_data.html)

I believe we might need to have different variants of the `media_profile` schema.

**Comment by N-Nagorny** [comment]
I think, it's a good idea to split the schema into multiple partial ones and leave `oneOf` in `media_profile` itself if you meant this.

**Comment by N-Nagorny** [comment]
I fixed it in #16. Take a look please.
